### ISSUE TITLE
what to do ?

### ISSUE THREAD

**Issue by Grace5921** [codevscolor/MaterialPreference#12]
```
12-22 02:39:53.306 19014-19014/? I/art: Late-enabling -Xcheck:jni
12-22 02:39:53.429 19014-19014/io.github.otaupdater.otaupdater W/System: ClassLoader referenced unknown path: /data/app/io.github.otaupdater.otaupdater-1/lib/arm
12-22 02:39:53.433 19014-19014/io.github.otaupdater.otaupdater I/InstantRun: Instant Run Runtime started. Android package is io.github.otaupdater.otaupdater, real application class is null.
12-22 02:39:54.421 19014-19014/io.github.otaupdater.otaupdater W/System: ClassLoader referenced unknown path: /data/app/io.github.otaupdater.otaupdater-1/lib/arm
12-22 02:39:54.751 19014-19014/io.github.otaupdater.otaupdater W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
12-22 02:39:55.242 19014-19125/io.github.otaupdater.otaupdater D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
12-22 02:39:55.249 19014-19124/io.github.otaupdater.otaupdater W/System: ClassLoader referenced unknown path: /system/framework/tcmclient.jar
12-22 02:39:55.296 19014-19125/io.github.otaupdater.otaupdater W/Adreno-GSL: <get_panel_settings:3802>: Android framework reported version 2. So, don't force ES30
12-22 02:39:55.297 19014-19125/io.github.otaupdater.otaupdater I/Adreno-EGL: <qeglDrvAPI_eglInitialize:381>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_KK_2.7_RB1.04.04.00.007.018_msm8960_KK_2.7_RB1_CL3869936_release_AU (CL3869936)
                                                                             OpenGL ES Shader Compiler Version: 17.01.10.SPL
                                                                             Build Date: 12/09/13 Mon
                                                                             Local Branch: mybranch2092625
                                                                             Remote Branch: quic/kk_2.7_rb1.15
                                                                             Local Patches: NONE
                                                                             Reconstruct Branch: AU_LINUX_ANDROID_KK_2.7_RB1.04.04.00.007.018 +  NOTHING
12-22 02:39:55.299 19014-19125/io.github.otaupdater.otaupdater I/OpenGLRenderer: Initialized EGL, version 1.4
12-22 02:39:56.837 19014-19014/io.github.otaupdater.otaupdater D/AndroidRuntime: Shutting down VM
12-22 02:39:56.842 19014-19014/io.github.otaupdater.otaupdater E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: io.github.otaupdater.otaupdater, PID: 19014
                                                                                 Theme: themes:{}
                                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.otaupdater.otaupdater/io.github.otaupdater.otaupdater.activity.SettingsActivity}: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Class is not a View com.codevscolor.materialpreference.widget.MaterialPreferenceCategory
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
                                                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                  Caused by: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Class is not a View com.codevscolor.materialpreference.widget.MaterialPreferenceCategory
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
                                                                                     at com.codevscolor.materialpreference.activity.MaterialMainActivity.onCreate(MaterialMainActivity.java:122)
                                                                                     at com.codevscolor.materialpreference.activity.MaterialPreferenceActivity.onCreate(MaterialPreferenceActivity.java:28)
                                                                                     at android.app.Activity.performCreate(Activity.java:6251)
                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
                                                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                  Caused by: android.view.InflateException: Binary XML file line #2: Class is not a View com.codevscolor.materialpreference.widget.MaterialPreferenceCategory
                                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:636)
                                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143) 
                                                                                     at com.codevscolor.materialpreference.activity.MaterialMainActivity.onCreate(MaterialMainActivity.java:122) 
                                                                                     at com.codevscolor.materialpreference.activity.MaterialPreferenceActivity.onCreate(MaterialPreferenceActivity.java:28) 
                                                                                     at android.app.Activity.performCreate(Activity.java:6251) 
                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403) 
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
                                                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                  Caused by: java.lang.ClassCastException: com.codevscolor.materialpreference.widget.MaterialPreferenceCategory cannot be cast to android.view.View
                                                                                     at java.lang.Class.asSubclass(Class.java:1486)
                                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:583)
                                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143) 
                                                                                     at com.codevscolor.materialpreference.activity.MaterialMainActivity.onCreate(MaterialMainActivity.java:122) 
                                                                                     at com.codevscolor.materialpreference.activity.MaterialPreferenceActivity.onCreate(MaterialPreferenceActivity.java:28) 
                                                                                     at android.app.Activity.performCreate(Activity.java:6251) 
                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403) 
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
                                                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
12-22 02:39:58.637 19014-19014/io.github.otaupdater.otaupdater I/Process: Sending signal. PID: 19014 SIG: 9
```

**Comment by codevscolor** [comment]
please post your init method and preference xml

**Comment by Grace5921** [comment]
sorry i deleted that and found other lib to to that any ways thanks for reply
