### ISSUE TITLE
NoSuchFieldError when try to open preference activity

### ISSUE THREAD

**Issue by laylizzlle** [codevscolor/MaterialPreference#5]
I get this when I try to open my activity that extends MaterialPreferenceActivity

```
java.lang.NoSuchFieldError: com.codevscolor.materialpreference.R$id.materialpref_toolbar
                                                                at com.codevscolor.materialpreference.activity.MaterialMainActivity.onCreate(MaterialMainActivity.java:123)
                                                                at com.codevscolor.materialpreference.activity.MaterialPreferenceActivity.onCreate(MaterialPreferenceActivity.java:28)
                                                                at android.app.Activity.performCreate(Activity.java:5451)
                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
                                                                at android.app.ActivityThread.access$900(ActivityThread.java:175)
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:146)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5602)
                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                at dalvik.system.NativeStart.main(Native Method)
```

**Comment by codevscolor** [comment]
are you using compile 'com.codevscolor.materialpreference:mp:0.2.1' ?
Please post your init method.

**Comment by codevscolor** [comment]
If you are not having this problem again , can we close it ?
