### ISSUE TITLE
 android.content.res.Resources$NotFoundException: Resource ID #0x0

### ISSUE THREAD

**Issue by emnrd-ito** [codevscolor/MaterialPreference#8]
I added this to my app build.grade:
    **compile 'com.codevscolor.materialpreference:mp:0.2.1'**
When I run I get this error:

>  java.lang.RuntimeException: Unable to start activity ComponentInfo{myapp.listemployees/myapp.listemployees.MaterialPreferences}: android.content.res.Resources$NotFoundException: Resource ID #0x0
>                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2802)
>                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867)
>                       at android.app.ActivityThread.access$900(ActivityThread.java:181)
>                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1476)
>                       at android.os.Handler.dispatchMessage(Handler.java:102)
>                       at android.os.Looper.loop(Looper.java:145)
>                       at android.app.ActivityThread.main(ActivityThread.java:6134)
>                       at java.lang.reflect.Method.invoke(Native Method)
>                       at java.lang.reflect.Method.invoke(Method.java:372)
>                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
>                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
>                    Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
>                       at android.content.res.Resources.getValue(Resources.java:2358)
>                       at android.content.res.Resources.loadXmlResourceParser(Resources.java:3958)
>                       at android.content.res.Resources.getXml(Resources.java:2223)
>                       at android.support.v7.preference.PreferenceInflater.inflate(PreferenceInflater.java:115)
>                       at android.support.v7.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:115)
>                       at android.support.v7.preference.PreferenceFragmentCompat.addPreferencesFromResource(PreferenceFragmentCompat.java:408)
>                       at com.codevscolor.materialpreference.fragment.MaterialPreferenceFragment.onCreate(MaterialPreferenceFragment.java:44)
>                       at android.support.v4.app.Fragment.performCreate(Fragment.java:2068)
>                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1055)
>                       at android.support.v4.app.BackStackRecord.setLastIn(BackStackRecord.java:838)
>                       at android.support.v4.app.BackStackRecord.calculateFragments(BackStackRecord.java:878)
>                       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:719)
>                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
>                       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
>                       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604)
>                       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
>                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234)
>                       at android.app.Activity.performStart(Activity.java:6412)
>                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2765)
>                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867) 
>                       at android.app.ActivityThread.access$900(ActivityThread.java:181) 
>                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1476) 
>                       at android.os.Handler.dispatchMessage(Handler.java:102) 
>                       at android.os.Looper.loop(Looper.java:145) 
>                       at android.app.ActivityThread.main(ActivityThread.java:6134) 
>                       at java.lang.reflect.Method.invoke(Native Method) 
>                       at java.lang.reflect.Method.invoke(Method.java:372) 
>                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
>                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
> 

I have the MaterialPreference project in Android Studio working standalone just fine. This occurs when including it as a dependency in an existing project.

I believe the problem is with my call to `setAppPackageName()`. I don't know what to put there.

**Comment by emnrd-ito** [comment]
Yes, that's it. I had to change the parameter to "com.myapp".  May I suggest you put a TODO comment on that line?
